# Generated by Django 3.1.5 on 2021-03-30 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FilterDemo',
            new_name='FilterModel',
        ),
    ]
